package Ecommerce.Product_Service.dto;


import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.SuperBuilder;

import java.util.List;

@SuperBuilder
@Data
@EqualsAndHashCode(callSuper = false)
public class CategoryExtendedResponse extends CategoryResponseDto {
    private  List<ProductResponseDto> products; // Assuming ProductResponseDto is defined elsewhere


    // Getters and Setters can be generated by Lombok or manually added if needed
}
